# Generated by Django 4.2 on 2023-04-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Joker",
            fields=[
                ("number", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.TextField()),
                (
                    "joker_type",
                    models.CharField(
                        blank=True,
                        choices=[("CHUCK", "Chuck"), ("DAD", "Dad")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "joker_id",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
            ],
        ),
    ]
